# helm -n vault upgrade --install vault-backup helm-chart -f values.yaml
cronjob:
  # schedule: 0 2 * * 6
  schedule: 0,5,10,15,20,25,30,35,40,45,50,55 * * * *
  # imageUpload: minio/mc:RELEASE.2023-03-23T20-03-04Z
  # imageUpload: minio/mc
  imageUpload: minio/mc:RELEASE.2022-12-12T19-27-27Z
  imageVault: hashicorp/vault:1.9.2
  imageConsul: hashicorp/consul:1.12.0
env:
  # VAULT_ADDR: 'http://vault.vault-test:8200'
  VAULT_ADDR: 'http://127.0.0.1:8200'
  VAULT_CACERT: '/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
  #CONSUL_HTTP_ADDR: 'http://consul-server.vault-test:8500'
  #CONSUL_CACERT: '/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
  VAULT_APPROLE_ROLE_ID: 'b4eb088f-5350-8225-282e-c1a235c161fc'
  VAULT_APPROLE_SECRET_ID: '7dbd1f89-f1f5-59b0-dba9-49ffc3f05c19'
  MOUNT_POINT: 'kv-v2'
  SECRET_PATH: 'devops-secret'
  BUCKET_NAME: 'test'
  MINIO_USERNAME: 'rootuser'
  MINIO_PASSWORD: 'rootpass123'
  MINIO_ADDR: 'minio-1681595552'
